### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by n0ts**
And update gemfile, thanks

### CODE REVIEW

**Comment by n0ts** [comment]
@jacobbednarz Could you enable Travis CI in this repository?

**Comment by jacobbednarz** [comment]
done! https://travis-ci.org/boxen/puppet-brewcask. i've kicked off a master build so the next push here should trigger.

**Comment by n0ts** [comment]
@jacobbednarz Thanks, Could you merge it?

**Comment by jacobbednarz** [comment]
:cake: thank you!

**Pull request merged**
