### PR TITLE
Support for caskroom/fonts

### PR DESCRIPTION
**Pull request by toolbear**
## Ideal

Allow [cask font install](https://github.com/caskroom/homebrew-fonts) analogous to app installs.

```yaml
# hiera/users/toolbear.yaml

boxen::personal::osx_apps:
  - 1password
  ...

boxen::personal::fonts
  - source-code-pro
```

* Tap `caskroom/fonts`
*  A separate `brewfont` provider
* implicit `font-` prefix so you say `source-code-pro` not `font-source-code-pro`

## Hacked together so far

With boxen/puppet-boxen#124

```yaml
boxen::personal::fonts:
  - source-code-pro
```

Behind the scenes it's still just a `Package[font-source-code-pro]` with `brewcask` provider.

## TODO

* [ ] agree on usage; backfill tests
* [ ] `brewfont` provider
* [x] add `boxen::personal::fonts` support to `personal.pp` (boxen/puppet-boxen#124)
* [ ] separation from `brewcask` provider so you can't install fonts with brewcask nor apps with brewfont

### CODE REVIEW

**Comment by tarebyte** [comment]
:+1: this is pretty neat, I'm excited to see the end result.

I currently just have a `fonts.pp` that I use to do that same thing

```puppet
class people::tarebyte::fonts {
  include homebrew
  include brewcask

  homebrew::tap { 'caskroom/fonts': }

  package { 'font-inconsolata-for-powerline': provider => 'brewcask' }
}
```

**Comment by toolbear** [comment]
Regarding:

> * [ ] separation from brewcask provider so you can't install fonts with brewcask nor apps with brew font

Is it enough that `boxen::personal::fonts` prefixes everything with `font-`, making it unlikely to mixup entries under `::osx_apps` and `::fonts`?

Once `caskroom/fonts` is tapped anywhere I see no way to prevent installation of `font-foo` with `::osx_apps`, but I also don't know that it matters.

**Comment by radeksimko** [comment]
@toolbear :+1: I like the idea, but there's a few more taps belonging to [caskroom](https://github.com/caskroom/) and I'd rather not end up tapping all of them while it may not be needed and generally taking more steps than user would normally do when not using boxen.

Any suggestions on how to make it optional with a meaningful API?

Is it worth making some king of proxy for `homebrew::tap { 'caskroom/*': }`? Something like `brewcask::tap { 'fonts': }? I'm eventually open for arguments why to keep it as it is.

**Comment by toolbear** [comment]
@radeksimko maybe that falls out naturally when making a `brewfont` provider instead of riding on the coattails of `brewcask`?

**Comment by radeksimko** [comment]
@toolbear Agreed, that might be even better solution, although I'm not sure about the suggested provider name.
It should not be confused with home(brew). Maybe `caskfont` or `caskroom-font` or `brewcask-font` (not sure which special characters are permitted and part of best practices though).

**Comment by jamieconnolly** [comment]
@toolbear @radeksimko — I'm all for something like this, but wouldn't having something like this in `puppet-boxen/manifests/personal.pp` solve the aforementioned issues?

```puppet
if count($fonts) > 0 { homebrew::tap { 'caskroom/fonts': } }
ensure_resource('package', $fonts, {
  'provider'        => 'brewcask',
})
```

**Comment by toolbear** [comment]
@jamieconnolly it would be nice if every consumer of this module didn't have to wrap `homebrew::tap` in a conditional before ensuring a font resource. There could be other uses outside of `personal.pp`.

That said, I'll make your change here and in my puppet-boxen PR as it's incrementally better than what I have now.

**Comment by radeksimko** [comment]
@jamieconnolly To be fair, that was my first thought when I saw this, but I think the suggested change will bring dependency on the `brewcask` module which may be necessary in the future anyway, because although brewcask will probably always be a `tap` for Homebrew, it does have plenty of custom functionality ([not dependent on homebrew](https://github.com/caskroom/homebrew-cask/pull/8089)) and therefore may need some extra module code which should not come into homebrew module.

There might be (and already are) people reporting issues to brewcask which belong to homebrew and vice versa and we should prevent these kind of situations by separating it.

**Comment by jamieconnolly** [comment]
@radeksimko I understand. I'm assuming then that caskroom fonts will always be implemented through `brewcask`? In that case I'm +1 on having the `brewcask::tap { 'fonts': }` proxy. And then we'd still be able to have the simple implementation in `personal.pp`, or am I missing something?

**Comment by radeksimko** [comment]
@jamieconnolly as mentioned above, @toolbear 's suggestion with custom font package provider could be better than my simple proxy as it will not only solve this issue, but also prevent users from using `brewcask` provider for fonts and forgetting to `tap` `caskroom/fonts` or running into some other strange errors...

**Comment by radeksimko** [comment]
Regarding provider per tap, it seems like a good solution (as an answer to @blackjid in #35 ).

Having said that, it would be nice to implement it in a way that we can easily allow user to use any of these without having to explicitly add support into the module.

The practice and common understanding is that `provider` = package manager (yum, apt, brew, ...). I know we're already kinda breaking this with brewcask provider, but I believe there are good reasons behind it. Brewcask really is providing something totally different from homebrew, but the other repositories are just _"flavours"_, they're not providing too different packages (in terms of how they're installed) from brewcask.

Maybe we could use the [`category`](https://docs.puppetlabs.com/references/latest/type.html#package-attribute-category) or any similar attribute (for the repository name or the whole string `github_org_name/repo_name`) and make it `caskroom/homebrew-cask` by default or something?

If we won't find a better way of implementing it, then custom provider for each repository will probably be a way to go. The user should be aware of where the package comes from and we should try to prevent things like these:

```
package { 'google-chrome': # actually coming from caskroom/homebrew-cask
    provider => 'homebrew'
}
package { 'adium-beta': # actually coming from caskroom/homebrew-versions
    provider => 'homebrew'
}
```

Users will always be allowed to write such code, but we should try to discourage people from doing so.

**Comment by toolbear** [comment]
To make sure I understand, @radeksimko, is it your suggestion that instead of creating a new provider, I modify `brewcask.rb` with support for fonts via `category => 'font'` or something similar?

**Comment by radeksimko** [comment]
@toolbear Yes, that is the idea along with reasons mentioned above, but I'm open for other suggestions/criticism if you think it's not the best way of dealing with it.

**Comment by toolbear** [comment]
@radeksimko I wasn't trying to imply criticism, only making sure I understood your suggestion.

**Comment by radeksimko** [comment]
Closing this in favor of https://github.com/boxen/puppet-brewcask/issues/35

Thanks for the PR, but it will need to be a bit more generic/sustainable as described above.

**Comment by toolbear** [comment]
No problem :panda_face:

**Pull request closed without merging**
