### PR TITLE
Allow for custom installs using a brewcask_root fact

### PR DESCRIPTION
**Pull request by jamieconnolly**
Similar to [puppet-homebrew](https://github.com/boxen/puppet-homebrew), this PR uses a `brewcask_root` fact to change the default installation directory.

It also updates the package provider to use the `homebrew_root` fact when determining the root directory of Homebrew. This fixes the issue when installing apps when homebrew isn't installed to `/opt/boxen/homebrew` (can be seen [here](https://github.com/boxen/puppet-boxen/pull/119#issuecomment-68036782)).

### CODE REVIEW

**Comment by radeksimko** [comment]
My only concern here and basically the reason it's taking so long to review/merge is the weight of proposed fact (`1`). It seems that @dgoodlad [has changed](https://github.com/boxen/puppet-boxen/commit/d2b9ecfb8cb4484a80f1762d5214625e8ecd4361) the default weights of external facts, and I was not able to test all corner cases yet. I want to know what does the change actually means for this fact and how does it limit the user in changing the value of it.

AFAIK it definitely prevents users from setting this fact from `~/.boxen/config.json` and some other user locations, **which might have actually been intention**, but I'm not sure.

**Comment by phinze** [comment]
FWIW I'm currently using this to set up my machine with homebrew in `/usr/local` and it seems to be working nicely.

**Comment by nolith** [comment]
Thank you so much!
Also for me this patch is working with homebrew in ```/usr/local```

**Comment by bval** [comment]
Running into exactly the same issue this fixes. Thanks, @jamieconnolly and :+1: on this.

**Pull request merged**
